[tool.poetry]
name = "air_collect"
version = "0.1.0"
description = "Local barometric pressure data collector using the DarkSky API"
authors = ["roboto84 <7658704+roboto84@users.noreply.github.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.4"
numpy = "^1.19.4"
requests = "^2.25.0"
python-dotenv = "^0.15.0"
APScheduler = "^3.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
